[package]
name = "link-explorer-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.18"
select = "0.5.0"
error-chain = "0.12.4"
tokio = { version = "1.18.2", features = ["full"] }